### ISSUE TITLE
There are dangerous commands in the installation script

### ISSUE THREAD

**Issue by heroacool** [Genesis-Embodied-AI/RoboGen#13]
![image](https://github.com/Genesis-Embodied-AI/RoboGen/assets/5468049/756da0ad-37dd-4ccd-b8a3-4c65407224cc)

it is not necessary!

**Comment by yufeiwang63** [comment]
Thanks for catching this! We copied the original installation commands from OMPL: https://ompl.kavrakilab.org/installation.html

It's good to know you don't have to run this for installing the package :)

I have updated the readme to reflect this.
