### ISSUE TITLE
cannot download the dataset

### ISSUE THREAD

**Issue by Guanbin-Huang** [Genesis-Embodied-AI/RoboGen#14]
<img width="1032" alt="image" src="https://github.com/Genesis-Embodied-AI/RoboGen/assets/30463291/213f950d-2ef4-427f-a231-0798793ec4dd">

file is not available in the site
<img width="320" alt="image" src="https://github.com/Genesis-Embodied-AI/RoboGen/assets/30463291/7917ec5c-fe0d-494c-bf17-0a771d9508a1">

**Comment by yufeiwang63** [comment]
Hmm, interesting. It works on my side, as shown in the following screenshots:

![image](https://github.com/Genesis-Embodied-AI/RoboGen/assets/37777198/3fa86d00-9286-4e95-a375-b2b351d1f2ac)
![image](https://github.com/Genesis-Embodied-AI/RoboGen/assets/37777198/1039477a-0292-4fdf-96eb-b071115c8c3f)

**Comment by Guanbin-Huang** [comment]
you can start to download it. but it ends up with around 92%, then it pops up the error.

**Comment by yufeiwang63** [comment]
The downloading finished correctly on my side. Could it be a network issue?
![image](https://github.com/Genesis-Embodied-AI/RoboGen/assets/37777198/1ac1900a-ec83-46d2-8699-a1f8f630faa7)

**Comment by Guanbin-Huang** [comment]
oh, maybe~,thanks
