### ISSUE TITLE
Issues Downloading Objaverse Dataset

### ISSUE THREAD

**Issue by Wesley-Le** [Genesis-Embodied-AI/RoboGen#17]
Hello 
I'm currently working on the Learn Skill project and facing difficulties in downloading the Objaverse dataset. Despite using proxies, the download consistently fails.
Could you please provide any advice or alternative methods for accessing the dataset? Any help or guidance would be greatly appreciated, as this dataset is essential for our project.
Thank you for your time and assistance.

**Comment by zhouxian** [comment]
What is the Learn Skill project?

**Comment by yufeiwang63** [comment]
Could you please provide more details on the failure? Which commands did you run and what error message was it?

**Comment by yufeiwang63** [comment]
Closed due to no detailed description of the issue.
