### ISSUE TITLE
Python OMPL Module issues on Windows

### ISSUE THREAD

**Issue by Captain-Freels** [Genesis-Embodied-AI/RoboGen#20]
I am having an issue getting the OMPL GUI to work on my computer. When I run 'ompl_app.py' from the software package, I get this error:

File "C:\vcpkg\buildtrees\omplapp\src\1.5.1-6c8b6a14e1.clean\gui\ompl_app.py", line 56, in
   from ompl.util import OutputHandler, useOutputHandler, LogLevel,
ModuleNotFoundError: No module named 'ompl'

I tried using pip to install it but it keeps saying it doesn't exist. What can I do to mend this?

**Comment by yufeiwang63** [comment]
There is probably some error in the OMPL installation. 
BTW, we are not using ompl_app.py for this project.

**Comment by Captain-Freels** [comment]
Would reinstalling just the bindings solve the issue? Also what do you mean for this project?

**Comment by Captain-Freels** [comment]
When I revisit the installation instructions, it says vcpkg does not contain the python bindings. What can I do to get said bindings or is there another way to run the GUI?

**Comment by yufeiwang63** [comment]
In this project we are using just the python bindings, not the GUI itself. So it won't be necessary to install the GUI if you want to use RoboGen.

**Comment by yufeiwang63** [comment]
Hi,

If you still have trouble installing ompl python binding from source, you can try installing it from the precompiled wheels, see the updated ReadMe for details.

**Comment by Captain-Freels** [comment]
Thank you, I will look into it when I get the chance and let you know.
