### ISSUE TITLE
Can I import different robots for use in this project? 

### ISSUE THREAD

**Issue by wfy1126** [Genesis-Embodied-AI/RoboGen#23]
I want to replace the robots in the project, but I don't know how to do it

**Comment by yufeiwang63** [comment]
You should be able to chnage the robots by using different urdf files of the robot. See this issue for more details: https://github.com/Genesis-Embodied-AI/RoboGen/issues/2

**Comment by wfy1126** [comment]
Thanks for your kind replies!

**Comment by wfy1126** [comment]
Hello, I noticed in your code that robots performing operational tasks rely on sliding for movement. I have a wheeled robot and I want it to move based on the rotation of the wheels. What modifications should I make. 

Looking forward to your reply.
Hello, I noticed in your code that robots performing operational tasks rely on sliding for movement. I have a wheeled robot and I want it to move based on the rotation of the wheels. What modifications should I make. Looking forward to your reply.

wufeiyang
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Genesis-Embodied-AI/RoboGen"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月2日(星期二) 凌晨3:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Genesis-Embodied-AI/RoboGen] Can I import different robots for use in this project?  (Issue #23)





 
You should be able to chnage the robots by using different urdf files of the robot. See this issue for more details: #2
