### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by StoneT2000** [Genesis-Embodied-AI/RoboGen#3]
Thanks for open sourcing your code! I got the following error while trying to use execute.py

```
FileNotFoundError: [Errno 2] No such file or directory: 'data/partnet_mobility_dict.json'
```

Any idea? I downloaded the partnet mobility dataset zip file from google drive but couldn't find this file

**Comment by yufeiwang63** [comment]
Thanks for catching this! The missing file has been added [here](https://github.com/Genesis-Embodied-AI/RoboGen/blob/main/data/partnet_mobility_dict.json)
