### ISSUE TITLE
Why sleep for 20 seconds before running the build_task_given_text() function?

### ISSUE THREAD

**Issue by dexin-wang** [Genesis-Embodied-AI/RoboGen#31]
Thanks for open sourcing this great work，I wonder Why sleep for 20 seconds before running the build_task_given_text() function? (gpt_4/prompts/prompt_manipulation.py, line 173)

https://github.com/Genesis-Embodied-AI/RoboGen/blob/486612cd0baa40857b561419c5a42fbb7e67724f/gpt_4/prompts/prompt_manipulation.py#L171-L182

**Comment by yufeiwang63** [comment]
hmmm I think back then there is a limit on how frequent you can call the GPT4 API, so I added a bit waiting time here. You can safely remove it -- I think it is likely that this won't be needed anymore.
